# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  # https://data.humdata.org/dataset/thailand-administrative-boundaries
  download:th:shp: wget https://data.humdata.org/dataset/d24bdc45-eb4c-4e3d-8b16-44db02667c27/resource/d0c722ff-6939-4423-ac0d-6501830b1759/download/tha_adm_rtsd_itos_20190221_shp_part_1.zip
