name: Update Thailand Covid Data
on:
  push:
    branches-ignore:
      - "releases/**"
  schedule: # can be up to 20min late. So better to have more updates
    - cron: "00 01 * * *" # 08:00 Unofficial tweet
    - cron: "25 05 * * *" # 12:25 daily briefing - official tweet
    - cron: "*/30 06-08 * * *" # Quick checks for briefing after 1pm
    # - cron: "00 06 * * *" # 13:00 daily briefing - briefing pdf
    # - cron: "40 06 * * *" # 13:40 daily briefing - briefing pdf
    # - cron: "50 07 * * *" # 14:50 in case briefing was uploaded late - #TODO: currently even later
#    - cron: "20 10 * * *" # 17:20 new PUI number
    - cron: "20 16 * * *" # 23:20 test data/situation report/vaccination report
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: |
          echo "::set-output name=date::$(TZ=Asia/Bangkok date +'%Y-%m-%d')"
          echo "::set-output name=yesterday::$(TZ=Asia/Bangkok date --date=yesterday +'%Y-%m-%d')"
          echo "::set-output name=month::$(TZ=Asia/Bangkok date +'%Y-%m')"
          echo "::set-output name=year::$(TZ=Asia/Bangkok date +'%Y')"
          echo "::set-output name=hour::$(TZ=Asia/Bangkok date +'%H')"
          echo "::set-output name=briefingurl::http://media.thaigov.go.th/uploads/public_img/source/$(TZ=Asia/Bangkok date +'%d%m')64.pdf"
          echo "::set-output name=briefingfile::briefings/$(TZ=Asia/Bangkok date +'%d%m')64.pdf"
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            **/*.pdf
            **/*.xlsx
            **/*.pptx
            **/*.pickle
            html/*
            json/*
            briefings/*
            tweets/*
            webdav/*
            situation_en/*
            situation_th/*
            testing_moph/*
            vaccinations/*
            ~/.cache/pip
            /tmp/tika-server.jar
            /tmp/tika-server.jar.md5
          key: ${{ runner.os }}-${{ steps.date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.date.outputs.date }}
            ${{ runner.os }}-${{ steps.date.outputs.yesterday }}
            ${{ runner.os }}-${{ steps.date.outputs.month }}
            ${{ runner.os }}-${{ steps.date.outputs.year }}
            ${{ runner.os }}
      - name: Check briefing doc available
        id: briefing
        continue-on-error: true
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["${{ steps.date.outputs.briefingurl }}"]'
          expected: '[301, 200]'
      - name: skip rest if schedule > 1pm and briefing not ready or done
        id: go
        if: ${{ github.event_name	!= 'schedule' || steps.date.outputs.hour < 13 || steps.briefing.outcome == 'success' && hashFiles(steps.date.outputs.briefingfile) == '' }}
        run: true        
      - name: Set up Python
        if: ${{ steps.go.outcome == 'success' }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/setup-java@v1
        if: ${{ steps.go.outcome == 'success' }}
        with:
          java-version: 15
      - name: Install dependencies
        if: ${{ steps.go.outcome == 'success' }}
        run: |
          sudo apt-get update
          sudo apt-get install ghostscript python3-tk
          pip install -r requirements.txt
      # - name: Check for updated data
      #   if: ${{ github.event_name	== 'schedule' }}
      #   run: |
      #       python covid_plot.py
      #   env:
      #       CHECK_NEWER: True 
      - name: Scape Covid Data
        id: update
        if: ${{ steps.go.outcome == 'success' }}
        run: |
            python covid_plot.py
      - name: Upload png to wiki
        if: ${{ steps.update.outcome == 'success' && github.ref == 'refs/heads/main' }}
        uses: kai-tub/external-repo-sync-action@v1
        with:
            source-directory: "outputs"
            include-patterns: "*.png"
        env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}      
      - name: Upload json to wiki
        if: ${{ steps.update.outcome == 'success' && github.ref == 'refs/heads/main' }}
        uses: kai-tub/external-repo-sync-action@v1
        with:
            source-directory: "api"
            include-patterns: "*"
        env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}      
