name: CI

on:
  push:
    branches-ignore:
      - "releases/**"
  schedule:
    - cron: "0 10 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/*.pdf
            ~/*.xlsx
            ~/.cache/pip
            /tmp/tika-server.jar
            /tmp/tika-server.jar.md5
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}
      - name: run
        run: |
            python covidthailand.py
      # - name: Upload Graphs
      #   if: success()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: graphs
      #     path: ./*.png
      # - name: Upload Graphs to wiki
      #   uses: SwiftDocOrg/github-wiki-publish-action@v1
      #   with:
      #     path: "*.png"
      #   env:
      #     GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
