name: Update Thailand Covid Data
on:
  push:
    branches-ignore:
      - "releases/**"
  schedule: # can be up to 20min late. So better to have more updates
    - cron: "50 23 * * *" # 08:00 Unofficial tweet - 1h earlier as gh is slow
    - cron: "25 05 * * *" # 12:25 daily briefing - official tweet
    - cron: "40 06 * * *" # 13:40 daily briefing - briefing pdf
    - cron: "50 07 * * *" # 14:50 in case briefing was uploaded late - #TODO: currently even later
    - cron: "20 10 * * *" # 17:20 new PUI number
    - cron: "20 16 * * *" # 23:20 test data/situation report/vaccination report
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Get current date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
          echo "::set-output name=yesterday::$(date --date=yesterday +'%Y-%m-%d')"
          echo "::set-output name=month::$(date +'%Y-%m')"
          echo "::set-output name=year::$(date +'%Y')"
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            **/*.pdf
            **/*.xlsx
            **/*.pptx
            **/*.pickle
            **/*.json
            **/*.csv
            html/*
            json/*
            ~/.cache/pip
            /tmp/tika-server.jar
            /tmp/tika-server.jar.md5
          key: ${{ runner.os }}-${{ steps.date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.date.outputs.date }}
            ${{ runner.os }}-${{ steps.date.outputs.yesterday }}
            ${{ runner.os }}-${{ steps.date.outputs.month }}
            ${{ runner.os }}-${{ steps.date.outputs.year }}
            ${{ runner.os }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ghostscript python3-tk
          pip install -r requirements.txt
      # - name: Check for updated data
      #   if: ${{ github.event_name	== 'schedule' }}
      #   run: |
      #       python covid_plot.py
      #   env:
      #       CHECK_NEWER: True 
      - name: Check for new data only
      #  if: ${{ github.event_name	!= 'schedule' }}
        run: |
            python covid_plot.py
      - name: Upload png to wiki
        if: success() && github.ref == 'refs/heads/main'
        uses: kai-tub/external-repo-sync-action@v1
        with:
            source-directory: "outputs"
            include-patterns: "*.png"
        env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}      
      - name: Upload json to wiki
        if: success() && github.ref == 'refs/heads/main'
        uses: kai-tub/external-repo-sync-action@v1
        with:
            source-directory: "api"
            include-patterns: "*"
        env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}      
